### ISSUE TITLE
Crash on ubuntu 14.04, file not found

### ISSUE THREAD

**Issue by brauliobo** [chef-cookbooks/locale#13]
On `/var/lib/locales/supported.d/local` I only have `pt` and `en`, not `local`

```
Recipe: <Dynamically Defined Resource>
  * ruby_block[add locale pt_BR] action run
================================================================================
Error executing action `run` on resource 'ruby_block[add locale pt_BR]'
================================================================================


ArgumentError
-------------
File '/var/lib/locales/supported.d/local' does not exist


Cookbook Trace:
---------------
/home/braulio/chef-solo/cookbooks-2/locales/providers/default.rb:79:in `new'
/home/braulio/chef-solo/cookbooks-2/locales/providers/default.rb:79:in `block (2 levels) in add_locale'


Resource Declaration:
---------------------
# In /home/braulio/chef-solo/cookbooks-2/locales/providers/default.rb

 77:   ruby_block "add locale #{locale}" do
 78:     block do
 79:       file = Chef::Util::FileEdit.new(node['locales']['locale_file'])
 80:       line = "#{high_locale(locale)} #{new_resource.charmap}"
 81:       file.insert_line_if_no_match(/^#{line}$/, line)
 82:       file.write_file
 83:     end
 84:     notifies :run, 'execute[locale-gen]', :immediate
 85:   end
 86: end



Compiled Resource:
# Declared in /home/braulio/chef-solo/cookbooks-2/locales/providers/default.rb:77:in `add_locale'

ruby_block("add locale pt_BR") do
  action "run"
  retries 0
  retry_delay 2
  guard_interpreter :default
  block_name "add locale pt_BR"
  cookbook_name :locales
  block #<Proc:0xb07901c@/home/braulio/chef-solo/cookbooks-2/locales/providers/default.rb:78>
end




Running handlers:
[2014-10-02T14:19:26-03:00] ERROR: Running exception handlers
Running handlers complete

```

**Comment by lamont-granquist** [comment]
doesn't make a lot of sense since you wound up in the redhat/centos block instead of the debian/ubuntu block.

i'm going to guess you were really using mint or raspbian or something and this will be solved by converting to properly using platform_family logic.
